import { NextResponse } from "next/server";

export const runtime = "nodejs"; // needed for FormData file handling

// ---- Config ----
const MAX_ATTACHMENT_BYTES = 5 * 1024 * 1024; // 5 MB
const ALLOWED_MIME = new Set([
  "application/pdf",
  "image/jpeg",
  "image/png",
  "image/webp",
]);

const CONTACT_TO =
  process.env.CONTACT_TO?.trim() || "hello@mistandember.com";
const CONTACT_FROM =
  process.env.CONTACT_FROM?.trim() || "Mist & Ember Exports <no-reply@mistandember.com>";
const RESEND_API_KEY = process.env.RESEND_API_KEY?.trim();

// ---- Utilities ----
function isValidEmail(s: string) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s);
}

function sanitize(s: unknown) {
  return String(s ?? "").trim();
}

async function fileToBase64(file: File) {
  const buf = Buffer.from(await file.arrayBuffer());
  return buf.toString("base64");
}

function htmlEscape(s: string) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function buildSubject(product: string | undefined, name: string) {
  return product
    ? `New enquiry — ${product} — ${name}`
    : `New enquiry — ${name}`;
}

function buildHtml(payload: Record<string, string>) {
  const rows = Object.entries(payload)
    .filter(([, v]) => v)
    .map(
      ([k, v]) =>
        `<tr><td style="padding:8px 12px;border:1px solid #eee;font-weight:600">${htmlEscape(
          k
        )}</td><td style="padding:8px 12px;border:1px solid #eee">${htmlEscape(
          v
        )}</td></tr>`
    )
    .join("");

  return `<!doctype html>
<html>
  <body style="font-family:ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial; color:#083335; background:#F6F3EE; padding:20px;">
    <div style="max-width:680px;margin:0 auto;background:#ffffff;border:1px solid #e7e3de;border-radius:12px;overflow:hidden">
      <div style="background:#083335;color:#F6F3EE;padding:16px 20px;font-size:16px;font-weight:700">
        Mist & Ember Exports — New Contact Enquiry
      </div>
      <div style="padding:20px">
        <p style="margin:0 0 12px 0;color:#4B5A56">You received a new enquiry from the website contact form.</p>
        <table style="border-collapse:collapse;width:100%;font-size:14px">${rows}</table>
        <p style="margin:16px 0 0 0;color:#9AA6A2;font-size:12px">This email was generated by the website API.</p>
      </div>
    </div>
  </body>
</html>`;
}

async function sendViaResend({
  to,
  from,
  subject,
  html,
  replyTo,
  attachment,
}: {
  to: string;
  from: string;
  subject: string;
  html: string;
  replyTo?: string;
  attachment?: { filename: string; content_base64: string; mime: string };
}) {
  if (!RESEND_API_KEY) {
    // Dev mode fallback
    console.warn("[contact] RESEND_API_KEY not set — running in dev log mode.");
    console.log(
      JSON.stringify(
        { to, from, subject, replyTo, hasAttachment: !!attachment },
        null,
        2
      )
    );
    return { ok: true, id: "dev-mode" as const };
  }

  // Resend API expects base64 attachments as { filename, content }
  const attachments = attachment
    ? [{ filename: attachment.filename, content: attachment.content_base64 }]
    : undefined;

  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${RESEND_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from,
      to: [to],
      subject,
      html,
      reply_to: replyTo,
      attachments,
    }),
  });

  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(
      `Resend error ${res.status}: ${text || res.statusText || "Unknown error"}`
    );
  }

  const data = (await res.json()) as { id?: string };
  return { ok: true, id: data.id || "sent" };
}

// ---- Route Handler ----
export async function POST(req: Request) {
  try {
    const ct = req.headers.get("content-type") || "";
    if (!ct.includes("multipart/form-data")) {
      return NextResponse.json(
        { ok: false, error: "Unsupported content type" },
        { status: 415 }
      );
    }

    const form = await req.formData();

    // Honeypot field (should be empty). Add a hidden input named "website".
    const honey = sanitize(form.get("website"));
    if (honey) {
      return NextResponse.json({ ok: true }); // Silently succeed for bots
    }

    const name = sanitize(form.get("name"));
    const company = sanitize(form.get("company"));
    const email = sanitize(form.get("email"));
    const phone = sanitize(form.get("phone"));
    const country = sanitize(form.get("country"));
    const product = sanitize(form.get("product"));
    const quantity = sanitize(form.get("quantity"));
    const message = sanitize(form.get("message"));

    // Basic validation
    const errors: Record<string, string> = {};
    if (!name) errors.name = "Name is required.";
    if (!email) errors.email = "Email is required.";
    else if (!isValidEmail(email)) errors.email = "Invalid email address.";
    if (!product) errors.product = "Product of interest is required.";
    if (!message) errors.message = "Message is required.";

    if (Object.keys(errors).length) {
      return NextResponse.json({ ok: false, errors }, { status: 400 });
    }

    // Optional file
    let attachment:
      | { filename: string; content_base64: string; mime: string }
      | undefined;

    const file = form.get("attachment");
    if (file && file instanceof File && file.size > 0) {
      if (file.size > MAX_ATTACHMENT_BYTES) {
        return NextResponse.json(
          { ok: false, error: "Attachment too large (max 5 MB)." },
          { status: 400 }
        );
      }
      if (!ALLOWED_MIME.has(file.type)) {
        return NextResponse.json(
          {
            ok: false,
            error:
              "Unsupported file type. Allowed: PDF, JPG, PNG, WEBP.",
          },
          { status: 400 }
        );
      }
      const filename = file.name || "attachment";
      const base64 = await fileToBase64(file);
      attachment = {
        filename,
        content_base64: base64,
        mime: file.type,
      };
    }

    // Build email
    const subject = buildSubject(product || undefined, name);
    const replyTo = email;
    const payload = {
      Name: name,
      Company: company,
      Email: email,
      Phone: phone,
      Country: country,
      "Product of Interest": product,
      "Quantity / Order Size": quantity,
      Message: message,
    };
    const html = buildHtml(payload);

    // Send
    const result = await sendViaResend({
      to: CONTACT_TO,
      from: CONTACT_FROM,
      subject,
      html,
      replyTo,
      ...(attachment != null && { attachment }),
    });

    return NextResponse.json({ ok: true, id: result.id });
  } catch (err: unknown) {
    console.error("[contact] error:", err);
    const msg =
      err instanceof Error ? err.message : "Unexpected server error.";
    return NextResponse.json({ ok: false, error: msg }, { status: 500 });
  }
}

// Optional: handle OPTIONS preflight if you ever post cross-origin
export async function OPTIONS() {
  return new NextResponse(null, {
    status: 204,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, Authorization",
    },
  });
}
